name: Test 🧪

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["Format Check 📝"]
    types:
      - completed

run-name: Test triggered by ${{ github.event_name }} - @${{ github.actor }}

jobs:
  test:
    name: Test on ${{ matrix.os }} with Zig ${{ matrix.zig-version }}
    runs-on: ${{ matrix.os }}
    if: |
      github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: [0.15.1]
        include:
          - os: ubuntu-latest
            zig-version: master
          - os: macos-latest
            zig-version: master
          - os: windows-latest
            zig-version: master
        exclude:
          # Scheduled jobs: exclude 0.15.1, only run master
          - os: ${{ github.event_name == 'schedule' && 'ubuntu-latest' || '' }}
            zig-version: ${{ github.event_name == 'schedule' && '0.15.1' || '' }}
          - os: ${{ github.event_name == 'schedule' && 'macos-latest' || '' }}
            zig-version: ${{ github.event_name == 'schedule' && '0.15.1' || '' }}
          - os: ${{ github.event_name == 'schedule' && 'windows-latest' || '' }}
            zig-version: ${{ github.event_name == 'schedule' && '0.15.1' || '' }}
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: zig build test --summary all
